/*
Deployment script for C:\USERS\DAVID\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\NOENTITIES\REFERENCEARCHITECTURE.TEST\DATABASE1.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\DAVID\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\NOENTITIES\REFERENCEARCHITECTURE.TEST\DATABASE1.MDF"
:setvar DefaultFilePrefix "C_\USERS\DAVID\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\NOENTITIES\REFERENCEARCHITECTURE.TEST\DATABASE1.MDF_"
:setvar DefaultDataPath "C:\Users\David\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\David\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [example].[Categories]...';


GO
CREATE TABLE [example].[Categories] (
    [Id]   INT          IDENTITY (1, 1) NOT NULL,
    [Name] VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[Complete]...';


GO
CREATE TABLE [example].[Complete] (
    [Id]               INT      IDENTITY (1, 1) NOT NULL,
    [TaskId]           INT      NOT NULL,
    [IsComplete]       BIT      NOT NULL,
    [FinalizationDate] DATETIME NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[Configuration]...';


GO
CREATE TABLE [example].[Configuration] (
    [Id]    INT          IDENTITY (1, 1) NOT NULL,
    [Key]   VARCHAR (50) NOT NULL,
    [Value] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[Highlight]...';


GO
CREATE TABLE [example].[Highlight] (
    [Id]     INT IDENTITY (1, 1) NOT NULL,
    [TaskId] INT NOT NULL,
    [Color]  INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[Projects]...';


GO
CREATE TABLE [example].[Projects] (
    [Id]               INT           IDENTITY (1, 1) NOT NULL,
    [Name]             VARCHAR (50)  NOT NULL,
    [Description]      VARCHAR (150) NOT NULL,
    [IsCompleted]      BIT           NOT NULL,
    [CreationDate]     DATETIME      NOT NULL,
    [FinalizationDate] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([Name] ASC)
);


GO
PRINT N'Creating [example].[Requirements]...';


GO
CREATE TABLE [example].[Requirements] (
    [Id]               INT           IDENTITY (1, 1) NOT NULL,
    [ProjectId]        INT           NOT NULL,
    [Name]             VARCHAR (50)  NOT NULL,
    [Description]      VARCHAR (150) NOT NULL,
    [IsComplete]       BIT           NOT NULL,
    [CreationDate]     DATETIME      NOT NULL,
    [FinalizationDate] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[Tasks]...';


GO
CREATE TABLE [example].[Tasks] (
    [Id]            INT           IDENTITY (1, 1) NOT NULL,
    [RequirementId] INT           NOT NULL,
    [Description]   VARCHAR (MAX) NOT NULL,
    [CreationDate]  DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[TasksCategories]...';


GO
CREATE TABLE [example].[TasksCategories] (
    [Id]           INT IDENTITY (1, 1) NOT NULL,
    [CategoriesId] INT NOT NULL,
    [TasksId]      INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [example].[Timer]...';


GO
CREATE TABLE [example].[Timer] (
    [Id]            INT IDENTITY (1, 1) NOT NULL,
    [TaskId]        INT NOT NULL,
    [TimeInSeconds] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating unnamed constraint on [example].[Complete]...';


GO
ALTER TABLE [example].[Complete] WITH NOCHECK
    ADD FOREIGN KEY ([TaskId]) REFERENCES [example].[Tasks] ([Id]);


GO
PRINT N'Creating unnamed constraint on [example].[Highlight]...';


GO
ALTER TABLE [example].[Highlight] WITH NOCHECK
    ADD FOREIGN KEY ([TaskId]) REFERENCES [example].[Tasks] ([Id]);


GO
PRINT N'Creating unnamed constraint on [example].[Requirements]...';


GO
ALTER TABLE [example].[Requirements] WITH NOCHECK
    ADD FOREIGN KEY ([ProjectId]) REFERENCES [example].[Projects] ([Id]);


GO
PRINT N'Creating unnamed constraint on [example].[Tasks]...';


GO
ALTER TABLE [example].[Tasks] WITH NOCHECK
    ADD FOREIGN KEY ([RequirementId]) REFERENCES [example].[Requirements] ([Id]);


GO
PRINT N'Creating unnamed constraint on [example].[TasksCategories]...';


GO
ALTER TABLE [example].[TasksCategories] WITH NOCHECK
    ADD FOREIGN KEY ([CategoriesId]) REFERENCES [example].[Categories] ([Id]);


GO
PRINT N'Creating unnamed constraint on [example].[TasksCategories]...';


GO
ALTER TABLE [example].[TasksCategories] WITH NOCHECK
    ADD FOREIGN KEY ([TasksId]) REFERENCES [example].[Tasks] ([Id]);


GO
PRINT N'Creating unnamed constraint on [example].[Timer]...';


GO
ALTER TABLE [example].[Timer] WITH NOCHECK
    ADD FOREIGN KEY ([TaskId]) REFERENCES [example].[Tasks] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'example.Complete'), OBJECT_ID(N'example.Highlight'), OBJECT_ID(N'example.Requirements'), OBJECT_ID(N'example.Tasks'), OBJECT_ID(N'example.TasksCategories'), OBJECT_ID(N'example.Timer'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
