//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoEstimates.repository._0.@__Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoEstimatesDevelopmentEntities : DbContext
    {
        public NoEstimatesDevelopmentEntities()
            : base("name=NoEstimatesDevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TasksCategory> TasksCategories { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Complete> Completes { get; set; }
        public virtual DbSet<Highlight> Highlights { get; set; }
        public virtual DbSet<Timer> Timers { get; set; }
    }
}
