//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoEstimates.repository._0.@__Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksCategory
    {
        public int Id { get; set; }
        public int CategoriesId { get; set; }
        public int TasksId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Task Task { get; set; }
    }
}
